-- Insertion dans la table `modele` si nécessaire
-- (N'utilisez cette section que si les modèles ne sont pas encore présents dans votre base de données)

ALTER TABLE modele AUTO_INCREMENT = 1;

INSERT INTO `modele` (`ID`, `NOM_MODELE`, `ID_CONSTRUCTEUR`) VALUES
                                                                 (1, 'Civic', 5),
                                                                 (2, 'Accord', 5),
                                                                 (3, 'Golf', 6),
                                                                 (4, 'Passat', 6),
                                                                 (5, 'Mustang', 4),
                                                                 (6, 'F-150', 4),
                                                                 (7, 'Camry', 2),
                                                                 (8, 'Corolla', 2),
                                                                 (9, '911', 21),
                                                                 (10, 'Panamera', 21),
                                                                 (11, 'A3', 22),
                                                                 (12, 'A4', 22),
                                                                 (13, 'Q7', 22),
                                                                 (14, 'Cherokee', 28),
                                                                 (15, 'Grand Cherokee', 28),
                                                                 (16, 'X5', 10),
                                                                 (17, 'X3', 10),
                                                                 (18, 'Model S', 14),
                                                                 (19, 'Model 3', 14),
                                                                 (20, 'Suburban', 54),
                                                                 (21, 'Silverado', 54),
                                                                 (22, 'Patriot', 28),
                                                                 (23, 'Renegade', 28),
                                                                 (24, 'F-Type', 15),
                                                                 (25, 'E-Pace', 15),
                                                                 (26, 'Alfa Giulia', 41),
                                                                 (27, 'Stelvio', 41),
                                                                 (28, 'Focus', 4),
                                                                 (29, 'Fiesta', 4),
                                                                 (30, 'LaFerrari', 32),
                                                                 (31, '488 GTB', 32),
                                                                 (32, 'Huracan', 33),
                                                                 (33, 'Aventador', 33),
                                                                 (34, '720S', 34),
                                                                 (35, '765LT', 34),
                                                                 (36, 'C_Two', 83),
                                                                 (37, 'ES8', 73),
                                                                 (38, 'P7', 74),
                                                                 (39, 'R1T', 75),
                                                                 (40, 'Air', 76),
                                                                 (41, 'Polestar 2', 77),
                                                                 (42, 'Revero', 88),
                                                                 (43, 'DB11', 31),
                                                                 (44, 'Vantage', 31),
                                                                 (45, 'Huayra', 35),
                                                                 (46, 'Jesko', 36),
                                                                 (47, 'Elise', 37),
                                                                 (48, '208', 38),
                                                                 (49, '3008', 38),
                                                                 (50, 'C3', 39);


ALTER TABLE fiche AUTO_INCREMENT = 1;

-- Insertion des fiches
INSERT INTO `fiche` (`ID`, `ID_CONSTRUCTEUR`, `ID_MODELE`, `ID_ANNEE_DEBUT`, `ID_ANNEE_FIN`, `ID_SEGMENT`, `NOM_FICHE`, `RESUME_FICHE`, `HISTOIRE_FICHE`, `DATE_AJOUT`, `ID_UTILISATEUR`) VALUES
                                                                                                                                                                                              (1, 5, 1, 1, 2, 3, 'Civic', 'Compacte sportive', '<p>La Civic est un modèle emblématique dans la catégorie des compactes. Connue pour son dynamisme et sa fiabilité, elle a évolué au fil des années pour intégrer les dernières technologies tout en conservant son caractère sportif.</p><p>La dernière version améliore le confort intérieur avec des matériaux de haute qualité et des options de connectivité avancées. La Civic offre également une conduite agile et une efficacité énergétique remarquable, ce qui en fait un choix populaire pour les conducteurs à la recherche d’un véhicule polyvalent.</p>', NOW(), 1),
                                                                                                                                                                                              (2, 5, 2, 1, 2, 4, 'Accord', 'Berline intermédiaire', '<p>L\'Accord est une berline intermédiaire reconnue pour son confort et sa qualité de conduite. Conçue pour offrir une expérience de conduite agréable, elle combine un design élégant avec des technologies modernes.</p><p>Les dernières versions de l\'Accord intègrent des améliorations notables en matière de sécurité, de performance et de confort, faisant de ce modèle un choix de premier ordre pour les familles et les professionnels.</p>', NOW(), 1),
                                                                                                                                                                                              (3, 6, 3, 1, 2, 5, 'Mustang', 'Coupé sportif', '<p>La Mustang est un coupé sportif iconique qui allie performance et style. Avec ses moteurs puissants et son design distinctif, elle est conçue pour offrir une conduite excitante et dynamique.</p><p>Les modèles récents continuent de repousser les limites avec des améliorations en termes de technologie et de confort, tout en maintenant l’essence même du sport automobile qui fait la renommée de la Mustang.</p>', NOW(), 1),
                                                                                                                                                                                              (4, 6, 4, 1, 2, 6, 'F-150', 'Pick-up robuste', '<p>Le F-150 est un pick-up robuste qui se distingue par sa capacité de chargement et ses performances tout-terrain. Conçu pour les tâches les plus exigeantes, il combine puissance et durabilité avec un confort accru pour les longues journées de travail.</p><p>Les dernières versions du F-150 intègrent des technologies avancées pour la sécurité et le confort, tout en continuant à offrir la robustesse qui a fait sa réputation.</p>', NOW(), 1),
                                                                                                                                                                                              (5, 7, 5, 1, 2, 7, 'Cherokee', 'SUV tout-terrain', '<p>Le Cherokee est un SUV tout-terrain qui allie confort et capacités de conduite en terrain difficile. Avec un design moderne et des caractéristiques de sécurité avancées, il est idéal pour les aventuriers et les familles.</p><p>Les modèles récents mettent l’accent sur l’amélioration de la technologie et du confort tout en conservant les compétences tout-terrain qui le définissent.</p>', NOW(), 1),
                                                                                                                                                                                              (6, 8, 6, 1, 2, 8, 'Grand Cherokee', 'SUV luxueux', '<p>Le Grand Cherokee est un SUV luxueux qui propose un intérieur raffiné et des caractéristiques de haute technologie. Avec ses capacités tout-terrain et son confort de conduite, il est conçu pour ceux qui recherchent à la fois luxe et performance.</p><p>Les dernières versions continuent d’améliorer le confort et la technologie tout en maintenant une excellente capacité tout-terrain.</p>', NOW(), 1),
                                                                                                                                                                                              (7, 9, 7, 1, 2, 1, 'Model S', 'Berline électrique', '<p>La Model S est une berline entièrement électrique qui offre des performances exceptionnelles et une autonomie impressionnante. Avec un design moderne et des caractéristiques de haute technologie, elle redéfinit le concept de la conduite électrique.</p><p>Les modèles récents continuent d’améliorer l’autonomie, la technologie et le confort, consolidant la position de la Model S comme une référence dans le marché des véhicules électriques.</p>', NOW(), 1),
                                                                                                                                                                                              (8, 10, 8, 1, 2, 2, 'Model X', 'SUV électrique', '<p>Le Model X est un SUV électrique qui combine luxe et innovation. Avec ses portes en ailes de faucon et ses caractéristiques de performance avancées, il offre une expérience de conduite unique.</p><p>Les versions récentes apportent des améliorations en matière de confort, de technologie et d’autonomie, offrant une alternative élégante aux SUV traditionnels.</p>', NOW(), 1),
                                                                                                                                                                                              (9, 11, 9, 1, 2, 3, 'Suburban', 'SUV grand format', '<p>Le Suburban est un SUV grand format qui offre un espace intérieur généreux et des capacités tout-terrain exceptionnelles. Conçu pour les familles et les aventuriers, il combine confort et fonctionnalité avec une performance robuste.</p><p>Les dernières versions améliorent le confort intérieur et la technologie tout en conservant ses capacités tout-terrain.</p>', NOW(), 1),
                                                                                                                                                                                              (10, 12, 10, 1, 2, 4, 'Silverado', 'Pick-up pleine grandeur', '<p>Le Silverado est un pick-up pleine grandeur qui se distingue par sa puissance et sa capacité de chargement. Avec un design robuste et des caractéristiques avancées, il est conçu pour les tâches les plus exigeantes.</p><p>Les modèles récents intègrent des technologies modernes pour le confort et la sécurité tout en maintenant une performance exceptionnelle.</p>', NOW(), 1),
                                                                                                                                                                                              (11, 13, 11, 1, 2, 5, 'Patriot', 'SUV compact', '<p>Le Patriot est un SUV compact qui allie style et fonctionnalité. Avec un design moderne et une capacité de conduite tout-terrain, il est parfait pour les aventures urbaines et rurales.</p><p>Les dernières versions mettent l’accent sur le confort et la technologie, offrant une expérience de conduite agréable et pratique.</p>', NOW(), 1),
                                                                                                                                                                                              (12, 14, 12, 1, 2, 6, 'Renegade', 'SUV compact', '<p>Le Renegade est un SUV compact qui offre une combinaison parfaite de style et de fonctionnalité. Avec ses caractéristiques modernes et son intérieur fonctionnel, il est idéal pour les conducteurs urbains et les aventuriers.</p><p>Les versions récentes continuent de renforcer ses capacités tout-terrain tout en offrant un confort amélioré.</p>', NOW(), 1),
                                                                                                                                                                                              (13, 15, 13, 1, 2, 7, 'F-Type', 'Coupé sportif', '<p>Le F-Type est un coupé sportif qui allie design élégant et performances exceptionnelles. Avec une gamme de moteurs puissants et un intérieur luxueux, il est conçu pour offrir une expérience de conduite exaltante.</p><p>Les modèles récents intègrent des technologies avancées et un confort accru pour les passionnés de conduite sportive.</p>', NOW(), 1),
                                                                                                                                                                                              (14, 16, 14, 1, 2, 8, 'XE', 'Berline sportive', '<p>Le XE est une berline sportive qui combine performances dynamiques et confort. Conçu pour les conducteurs recherchant une expérience de conduite active, il propose un design moderne et des caractéristiques haut de gamme.</p><p>Les versions récentes améliorent la technologie et la sécurité tout en offrant une conduite raffinée.</p>', NOW(), 1),
                                                                                                                                                                                              (15, 17, 15, 1, 2, 1, '488 Pista', 'Supercar', '<p>La 488 Pista est une supercar qui offre des performances exceptionnelles et un design aérodynamique. Conçue pour les passionnés de vitesse et de technologie, elle combine puissance brute et sophistication.</p><p>Les modèles récents intègrent des améliorations en matière de confort et de technologie tout en maintenant un design distinctif.</p>', NOW(), 1),
                                                                                                                                                                                              (16, 18, 16, 1, 2, 2, 'Stelvio', 'SUV sportif', '<p>Le Stelvio est un SUV sportif qui propose une combinaison unique de performance et de fonctionnalité. Conçu pour offrir une conduite dynamique tout en offrant un espace intérieur généreux, il est un choix populaire parmi les SUV de luxe.</p><p>Les modèles récents mettent l’accent sur la technologie et le confort, avec des caractéristiques modernes pour une expérience de conduite haut de gamme.</p>', NOW(), 1),
                                                                                                                                                                                              (17, 19, 17, 1, 2, 3, 'Focus', 'Compacte', '<p>La Focus est une compacte qui offre un excellent compromis entre performance et confort. Depuis ses débuts, elle a été conçue pour répondre aux besoins des conducteurs recherchant une conduite agile et une technologie avancée.</p><p>Les dernières versions continuent d’améliorer le confort et la technologie tout en maintenant une excellente performance sur route.</p>', NOW(), 1),
                                                                                                                                                                                              (18, 20, 18, 1, 2, 4, 'A6', 'Berline', '<p>L\'A6 est une berline qui combine luxe et performance. Avec un intérieur raffiné et des caractéristiques de conduite avancées, elle est conçue pour offrir un confort optimal et une expérience de conduite agréable.</p><p>Les modèles récents mettent l’accent sur les technologies modernes et les améliorations en matière de confort et de sécurité.</p>', NOW(), 1),
(19, 21, 19, 1, 2, 5, 'Q5', 'SUV', '<p>Le Q5 est un SUV qui allie confort et performance. Avec un design élégant et des caractéristiques modernes, il est conçu pour offrir une conduite agréable et un espace intérieur généreux.</p><p>Les versions récentes continuent de promouvoir l’innovation et le confort tout en offrant une conduite raffinée.</p>', NOW(), 1),
(20, 22, 20, 1, 2, 6, 'G-Class', 'SUV luxe', '<p>La G-Class est un SUV de luxe qui allie robustesse et sophistication. Avec son design emblématique et ses caractéristiques de conduite tout-terrain, elle est conçue pour ceux qui recherchent à la fois luxe et performance.</p><p>Les modèles récents améliorent le confort et la technologie tout en maintenant une excellente capacité tout-terrain.</p>', NOW(), 1),
(21, 23, 21, 1, 2, 7, 'X5', 'SUV premium', '<p>Le X5 est un SUV premium qui offre une expérience de conduite haut de gamme. Avec un intérieur luxueux et des performances exceptionnelles, il est conçu pour les conducteurs exigeants.</p><p>Les versions récentes mettent l’accent sur la technologie, le confort et la performance pour une expérience de conduite raffinée.</p>', NOW(), 1),
(22, 24, 22, 1, 2, 8, 'V60', 'Break', '<p>Le V60 est un break qui combine praticité et confort. Avec un design moderne et une capacité de chargement généreuse, il est idéal pour les familles et les conducteurs recherchant un véhicule spacieux.</p><p>Les modèles récents améliorent le confort intérieur et la technologie tout en offrant une performance équilibrée.</p>', NOW(), 1),
(23, 25, 23, 1, 2, 1, 'Panamera', 'Berline de luxe', '<p>La Panamera est une berline de luxe qui allie performance sportive et confort. Avec un design élégant et des caractéristiques haut de gamme, elle est conçue pour offrir une expérience de conduite exceptionnelle.</p><p>Les modèles récents continuent d’améliorer la technologie et le confort tout en offrant des performances remarquables.</p>', NOW(), 1),
(24, 26, 24, 1, 2, 2, 'Aston Martin DB11', 'Supercar', '<p>L\'Aston Martin DB11 est une supercar qui combine luxe et performance. Avec un design époustouflant et des caractéristiques de conduite avancées, elle est conçue pour offrir une expérience de conduite ultime.</p><p>Les modèles récents intègrent des technologies modernes pour le confort et la performance, faisant de la DB11 un choix exceptionnel dans le monde des supercars.</p>', NOW(), 1),
                                                                                                                                                                                              (25, 27, 25, 1, 2, 3, 'LaFerrari', 'Supercar', '<p>La LaFerrari est une supercar qui offre des performances inégalées et un design avant-gardiste. Conçue pour les passionnés de vitesse, elle combine puissance et technologie de pointe pour offrir une expérience de conduite unique.</p><p>Les modèles récents continuent d’améliorer les performances tout en offrant un confort et une sophistication exceptionnels.</p>', NOW(), 1),
                                                                                                                                                                                              (26, 28, 26, 1, 2, 4, 'F-PACE', 'SUV premium', '<p>Le F-PACE est un SUV premium qui propose un équilibre parfait entre performance et confort. Avec un design moderne et des caractéristiques de conduite avancées, il est idéal pour ceux qui recherchent une expérience de conduite haut de gamme.</p><p>Les versions récentes continuent de mettre l’accent sur la technologie et le confort, tout en offrant une performance exceptionnelle.</p>', NOW(), 1),
                                                                                                                                                                                              (27, 29, 27, 1, 2, 5, 'E-PACE', 'SUV compact', '<p>L\'E-PACE est un SUV compact qui allie style et performance. Avec un design moderne et des caractéristiques de conduite sportives, il est conçu pour offrir une expérience de conduite agréable tout en offrant une praticité accrue.</p><p>Les modèles récents intègrent des améliorations en matière de technologie et de confort tout en maintenant une performance dynamique.</p>', NOW(), 1),
(28, 30, 28, 1, 2, 6, 'I-PACE', 'SUV électrique', '<p>L\'I-PACE est un SUV électrique qui propose une conduite raffinée avec une autonomie impressionnante. Avec un design moderne et des caractéristiques haut de gamme, il est conçu pour offrir une expérience de conduite élégante et durable.</p><p>Les dernières versions mettent l’accent sur le confort et la technologie tout en offrant une performance électrique exceptionnelle.</p>', NOW(), 1),
                                                                                                                                                                                              (29, 31, 29, 1, 2, 7, 'Jetta', 'Berline compacte', '<p>Le Jetta est une berline compacte qui combine confort et performance. Avec un design moderne et des caractéristiques de conduite avancées, il est conçu pour offrir une expérience de conduite agréable et dynamique.</p><p>Les modèles récents continuent d’améliorer le confort et la technologie tout en maintenant une performance équilibrée.</p>', NOW(), 1),
                                                                                                                                                                                              (30, 32, 30, 1, 2, 8, 'Golf', 'Compacte', '<p>La Golf est une compacte qui allie style et performance. Avec un design élégant et des caractéristiques modernes, elle est conçue pour offrir une expérience de conduite agréable tout en restant pratique.</p><p>Les versions récentes intègrent des améliorations en matière de confort et de technologie tout en offrant une performance exceptionnelle.</p>', NOW(), 1),
                                                                                                                                                                                              (31, 33, 31, 1, 2, 1, 'X3', 'SUV', '<p>Le X3 est un SUV qui propose une expérience de conduite confortable et dynamique. Avec un design moderne et des caractéristiques de haute technologie, il est idéal pour ceux qui recherchent un SUV offrant à la fois luxe et performance.</p><p>Les dernières versions mettent l’accent sur le confort et la technologie tout en offrant des performances exceptionnelles.</p>', NOW(), 1),
                                                                                                                                                                                              (32, 34, 32, 1, 2, 2, 'X4', 'SUV compact', '<p>Le X4 est un SUV compact qui combine performance et design. Avec un intérieur raffiné et des caractéristiques de conduite sportives, il est idéal pour ceux qui recherchent une conduite dynamique et un confort élevé.</p><p>Les versions récentes améliorent la technologie et la sécurité tout en maintenant un design élégant.</p>', NOW(), 1),
                                                                                                                                                                                              (33, 35, 33, 1, 2, 3, 'X5', 'SUV premium', '<p>Le X5 est un SUV premium qui offre une expérience de conduite haut de gamme. Avec un intérieur luxueux et des performances exceptionnelles, il est conçu pour les conducteurs exigeants.</p><p>Les versions récentes mettent l’accent sur la technologie, le confort et la performance pour une expérience de conduite raffinée.</p>', NOW(), 1),
                                                                                                                                                                                              (34, 36, 34, 1, 2, 4, 'X6', 'SUV grand luxe', '<p>Le X6 est un SUV grand luxe qui allie performance et élégance. Avec son design distinctif et ses caractéristiques de confort haut de gamme, il est conçu pour ceux qui recherchent à la fois style et fonctionnalité.</p><p>Les modèles récents améliorent la technologie et le confort tout en offrant des performances exceptionnelles.</p>', NOW(), 1),
                                                                                                                                                                                              (35, 37, 35, 1, 2, 5, 'X7', 'SUV grand format', '<p>Le X7 est un SUV grand format qui offre un espace intérieur luxueux et des performances exceptionnelles. Conçu pour les familles et les aventuriers, il propose un confort inégalé et des caractéristiques modernes.</p><p>Les modèles récents intègrent des technologies de pointe pour le confort et la sécurité, tout en offrant un design moderne et imposant.</p>', NOW(), 1),
                                                                                                                                                                                              (36, 38, 36, 1, 2, 6, 'Q4 E-Tron', 'SUV électrique', '<p>Le Q4 E-Tron est un SUV compact électrique qui allie performance et praticité. Conçu pour offrir une expérience de conduite moderne avec une autonomie accrue, il propose des caractéristiques de confort et de technologie avancées.</p><p>Les versions récentes continuent de mettre l’accent sur l’efficacité énergétique tout en offrant un design élégant et moderne.</p>', NOW(), 1),
                                                                                                                                                                                              (37, 39, 37, 1, 2, 7, 'A3', 'Berline compacte', '<p>L\'A3 est une berline compacte qui combine luxe et performance. Avec un design moderne et des caractéristiques de conduite avancées, elle est conçue pour offrir une expérience de conduite dynamique et confortable.</p><p>Les modèles récents continuent de renforcer le confort et la technologie tout en offrant une performance équilibrée.</p>', NOW(), 1),
(38, 40, 38, 1, 2, 8, 'A4', 'Berline', '<p>L\'A4 est une berline qui allie performance et luxe. Avec un intérieur raffiné et des caractéristiques modernes, elle est conçue pour offrir un confort optimal et une conduite agréable.</p><p>Les versions récentes améliorent la technologie et le confort tout en maintenant des performances exceptionnelles.</p>', NOW(), 1),
                                                                                                                                                                                              (39, 41, 39, 1, 2, 1, 'C-Class', 'Berline', '<p>La C-Class est une berline qui propose une combinaison parfaite de luxe et de performance. Avec un design élégant et des technologies avancées, elle est conçue pour offrir une expérience de conduite raffinée.</p><p>Les modèles récents mettent l’accent sur la technologie et le confort, tout en offrant des performances impressionnantes.</p>', NOW(), 1),
                                                                                                                                                                                              (40, 42, 40, 1, 2, 2, 'E-Class', 'Berline', '<p>L\'E-Class est une berline de luxe qui allie confort et technologie. Avec un intérieur spacieux et des caractéristiques modernes, elle est conçue pour offrir une conduite agréable et une expérience de luxe.</p><p>Les modèles récents continuent de renforcer le confort et la technologie tout en offrant des performances remarquables.</p>', NOW(), 1),
(41, 43, 41, 1, 2, 3, 'S-Class', 'Berline de luxe', '<p>L\'S-Class est une berline de luxe qui représente le summum du confort et de la technologie. Avec des caractéristiques haut de gamme et un design raffiné, elle est conçue pour offrir une expérience de conduite ultime.</p><p>Les dernières versions continuent d’améliorer la technologie et le confort tout en offrant des performances exceptionnelles.</p>', NOW(), 1),
                                                                                                                                                                                              (42, 44, 42, 1, 2, 4, 'GLS', 'SUV grand luxe', '<p>Le GLS est un SUV grand luxe qui propose un espace intérieur spacieux et des caractéristiques de confort avancées. Conçu pour les familles et les conducteurs exigeants, il combine performance et luxe.</p><p>Les modèles récents intègrent des améliorations en matière de confort et de technologie tout en offrant des performances exceptionnelles.</p>', NOW(), 1),
                                                                                                                                                                                              (43, 45, 43, 1, 2, 5, 'G-Class', 'SUV luxe', '<p>La G-Class est un SUV de luxe qui allie robustesse et sophistication. Avec son design emblématique et ses caractéristiques de conduite tout-terrain, elle est conçue pour ceux qui recherchent à la fois luxe et performance.</p><p>Les modèles récents améliorent le confort et la technologie tout en maintenant une excellente capacité tout-terrain.</p>', NOW(), 1),
                                                                                                                                                                                              (44, 46, 44, 1, 2, 6, '7 Series', 'Berline luxe', '<p>La 7 Series est une berline de luxe qui propose une expérience de conduite haut de gamme avec un intérieur spacieux et raffiné. Conçue pour offrir confort et technologie, elle est idéale pour les conducteurs exigeants.</p><p>Les dernières versions continuent d’améliorer le confort et la technologie tout en offrant des performances exceptionnelles.</p>', NOW(), 1),
                                                                                                                                                                                              (45, 47, 45, 1, 2, 7, '8 Series', 'Coupé luxe', '<p>L\'8 Series est un coupé luxe qui combine performance et élégance. Avec un design moderne et des caractéristiques de conduite avancées, elle est conçue pour offrir une expérience de conduite exceptionnelle.</p><p>Les modèles récents intègrent des technologies modernes pour le confort et la performance, consolidant ainsi la position de l\'8 Series comme une référence dans le monde des coupés de luxe.</p>', NOW(), 1),
                                                                                                                                                                                              (46, 48, 46, 1, 2, 8, 'M5', 'Berline sportive', '<p>La M5 est une berline sportive qui allie puissance et confort. Avec un design dynamique et des performances impressionnantes, elle est conçue pour offrir une expérience de conduite exaltante.</p><p>Les modèles récents continuent d’améliorer la technologie et le confort tout en offrant des performances exceptionnelles.</p>', NOW(), 1),
                                                                                                                                                                                              (47, 49, 47, 1, 2, 1, 'X1', 'SUV compact', '<p>Le X1 est un SUV compact qui propose une conduite agréable avec un design moderne et des caractéristiques de confort avancées. Idéal pour les conducteurs urbains, il combine praticité et style.</p><p>Les dernières versions intègrent des améliorations en matière de technologie et de confort, offrant une expérience de conduite raffinée.</p>', NOW(), 1),
                                                                                                                                                                                              (48, 50, 48, 1, 2, 2, 'Z4', 'Coupé sport', '<p>Le Z4 est un coupé sport qui allie performance et design. Avec un moteur puissant et un intérieur raffiné, il est conçu pour offrir une expérience de conduite dynamique.</p><p>Les modèles récents mettent l’accent sur le confort et la technologie tout en offrant des performances exceptionnelles sur route.</p>', NOW(), 1),
                                                                                                                                                                                              (49, 51, 49, 1, 2, 3, 'R8', 'Supercar', '<p>La R8 est une supercar qui propose des performances époustouflantes et un design innovant. Avec une puissance brute et une technologie de pointe, elle est conçue pour les passionnés de vitesse.</p><p>Les modèles récents continuent d’offrir des performances exceptionnelles tout en intégrant des améliorations en matière de confort et de technologie.</p>', NOW(), 1),
                                                                                                                                                                                              (50, 52, 50, 1, 2, 4, 'Taycan', 'Berline électrique', '<p>Le Taycan est une berline électrique qui offre des performances impressionnantes avec une autonomie élevée. Avec un design moderne et des caractéristiques de haute technologie, il est conçu pour les conducteurs à la recherche d’une expérience de conduite électrique raffinée.</p><p>Les versions récentes améliorent la technologie et le confort tout en offrant des performances de conduite exceptionnelles.</p>', NOW(), 1);

ALTER TABLE version AUTO_INCREMENT = 1;

-- Insertion des versions pour chaque fiche
INSERT INTO `version` (`ID`, `ID_FICHE`, `APPELLATION`, `CARBURANT`, `CONSTRUCTION_ANNEE`, `NOM_MOTEUR`, `CYLINDREE`, `PERFORMANCE`, `COUPLE`, `ZERO_A_100`, `VMAX`, `CONSOMMATION`, `CARROSSERIE`, `MARCHE_CONTINENT`) VALUES
                                                                                                                                                                                                                            (1, 1, 'Civic 1.5T', 'Essence', '2020', 'VTEC Turbo', '1498 cm³', '180 ch', '240 Nm', '8.0 s', '220 km/h', '6.5 L/100 km', 'Berline', 'Europe'),
                                                                                                                                                                                                                            (2, 1, 'Civic 2.0', 'Essence', '2021', 'Atkinson', '1996 cm³', '158 ch', '190 Nm', '9.0 s', '210 km/h', '7.0 L/100 km', 'Berline', 'Amérique du Nord'),
                                                                                                                                                                                                                            (3, 2, 'Corolla 1.8', 'Essence', '2020', '4 cylindres', '1798 cm³', '139 ch', '176 Nm', '10.2 s', '200 km/h', '7.5 L/100 km', 'Compacte', 'Europe'),
                                                                                                                                                                                                                            (4, 2, 'Corolla 2.0', 'Essence', '2021', 'Dynamic Force', '1987 cm³', '169 ch', '200 Nm', '8.5 s', '210 km/h', '6.8 L/100 km', 'Compacte', 'Asie'),
                                                                                                                                                                                                                            (5, 3, 'Mustang EcoBoost', 'Essence', '2020', '4 cylindres turbo', '1999 cm³', '310 ch', '430 Nm', '5.5 s', '250 km/h', '8.0 L/100 km', 'Coupé', 'Amérique du Nord'),
                                                                                                                                                                                                                            (6, 3, 'Mustang GT', 'Essence', '2021', 'V8', '5026 cm³', '450 ch', '556 Nm', '4.8 s', '260 km/h', '12.0 L/100 km', 'Coupé', 'Europe'),
                                                                                                                                                                                                                            (7, 4, 'Cayenne Turbo', 'Essence', '2020', 'V8', '3996 cm³', '541 ch', '770 Nm', '4.1 s', '290 km/h', '11.0 L/100 km', 'SUV', 'Europe'),
                                                                                                                                                                                                                            (8, 4, 'Cayenne E-Hybrid', 'Hybride', '2021', 'V6 + électrique', '2995 cm³', '455 ch', '700 Nm', '5.0 s', '250 km/h', '9.0 L/100 km', 'SUV', 'Amérique du Nord'),
                                                                                                                                                                                                                            (9, 5, 'X5 xDrive40i', 'Essence', '2020', '6 cylindres en ligne', '2998 cm³', '335 ch', '450 Nm', '5.3 s', '250 km/h', '10.0 L/100 km', 'SUV', 'Europe'),
                                                                                                                                                                                                                            (10, 5, 'X5 xDrive50i', 'Essence', '2021', 'V8', '4395 cm³', '456 ch', '650 Nm', '4.7 s', '270 km/h', '12.5 L/100 km', 'SUV', 'Amérique du Nord'),
                                                                                                                                                                                                                            (11, 6, '911 Carrera', 'Essence', '2020', '6 cylindres', '2981 cm³', '379 ch', '450 Nm', '4.2 s', '290 km/h', '9.0 L/100 km', 'Coupé', 'Europe'),
                                                                                                                                                                                                                            (12, 6, '911 Turbo S', 'Essence', '2021', '6 cylindres', '3745 cm³', '641 ch', '800 Nm', '2.7 s', '320 km/h', '12.0 L/100 km', 'Coupé', 'Amérique du Nord'),
                                                                                                                                                                                                                            (13, 7, 'A4 Avant 2.0 TFSI', 'Essence', '2020', '4 cylindres turbo', '1984 cm³', '248 ch', '370 Nm', '6.0 s', '250 km/h', '8.5 L/100 km', 'Break', 'Europe'),
                                                                                                                                                                                                                            (14, 7, 'A4 Avant 2.0 TDI', 'Diesel', '2021', '4 cylindres', '1968 cm³', '190 ch', '400 Nm', '7.5 s', '240 km/h', '5.5 L/100 km', 'Break', 'Amérique du Nord'),
                                                                                                                                                                                                                            (15, 8, 'Q5 55 TFSI', 'Essence', '2020', 'V6', '2995 cm³', '362 ch', '500 Nm', '5.9 s', '250 km/h', '10.0 L/100 km', 'SUV', 'Europe'),
                                                                                                                                                                                                                            (16, 8, 'Q5 40 TDI', 'Diesel', '2021', '4 cylindres', '1968 cm³', '204 ch', '400 Nm', '7.2 s', '220 km/h', '6.5 L/100 km', 'SUV', 'Asie'),
                                                                                                                                                                                                                            (17, 9, 'G-Class G 550', 'Essence', '2020', 'V8', '3982 cm³', '416 ch', '610 Nm', '5.6 s', '220 km/h', '13.0 L/100 km', 'SUV', 'Europe'),
                                                                                                                                                                                                                            (18, 9, 'G-Class G 63 AMG', 'Essence', '2021', 'V8', '3982 cm³', '577 ch', '850 Nm', '4.5 s', '240 km/h', '15.0 L/100 km', 'SUV', 'Amérique du Nord'),
                                                                                                                                                                                                                            (19, 10, 'X1 xDrive28i', 'Essence', '2020', '4 cylindres turbo', '1998 cm³', '228 ch', '350 Nm', '6.3 s', '235 km/h', '7.5 L/100 km', 'SUV', 'Europe'),
                                                                                                                                                                                                                            (20, 10, 'X1 xDrive25d', 'Diesel', '2021', '4 cylindres', '1995 cm³', '231 ch', '450 Nm', '6.5 s', '220 km/h', '5.0 L/100 km', 'SUV', 'Asie'),
                                                                                                                                                                                                                            (21, 11, 'V60 T5', 'Essence', '2020', '4 cylindres turbo', '1969 cm³', '250 ch', '360 Nm', '6.2 s', '250 km/h', '8.0 L/100 km', 'Break', 'Europe'),
                                                                                                                                                                                                                            (22, 11, 'V60 T8', 'Hybride', '2021', '4 cylindres + électrique', '1969 cm³', '390 ch', '640 Nm', '4.5 s', '240 km/h', '7.5 L/100 km', 'Break', 'Amérique du Nord'),
                                                                                                                                                                                                                            (23, 12, 'Panamera 4', 'Essence', '2020', 'V6', '2960 cm³', '330 ch', '450 Nm', '5.4 s', '250 km/h', '9.0 L/100 km', 'Berline', 'Europe'),
                                                                                                                                                                                                                            (24, 12, 'Panamera Turbo', 'Essence', '2021', 'V8', '3996 cm³', '550 ch', '770 Nm', '3.6 s', '290 km/h', '11.5 L/100 km', 'Berline', 'Amérique du Nord'),
                                                                                                                                                                                                                            (25, 13, 'DB11 V8', 'Essence', '2020', 'V8', '3988 cm³', '503 ch', '675 Nm', '4.0 s', '300 km/h', '12.0 L/100 km', 'Coupé', 'Europe'),
                                                                                                                                                                                                                            (26, 13, 'DB11 V12', 'Essence', '2021', 'V12', '5204 cm³', '600 ch', '700 Nm', '3.7 s', '310 km/h', '14.0 L/100 km', 'Coupé', 'Amérique du Nord'),
                                                                                                                                                                                                                            (27, 14, 'LaFerrari Aperta', 'Essence', '2020', 'V12 + électrique', '6262 cm³', '950 ch', '900 Nm', '2.9 s', '352 km/h', '15.0 L/100 km', 'Coupé', 'Europe'),
                                                                                                                                                                                                                            (28, 14, 'LaFerrari', 'Essence', '2021', 'V12 + électrique', '6262 cm³', '950 ch', '900 Nm', '2.6 s', '350 km/h', '14.0 L/100 km', 'Coupé', 'Asie'),
                                                                                                                                                                                                                            (29, 15, 'A8 55 TFSI', 'Essence', '2020', 'V6', '2995 cm³', '335 ch', '500 Nm', '5.6 s', '250 km/h', '10.5 L/100 km', 'Berline', 'Europe'),
                                                                                                                                                                                                                            (30, 15, 'A8 60 TDI', 'Diesel', '2021', 'V6', '3130 cm³', '420 ch', '600 Nm', '5.0 s', '250 km/h', '9.0 L/100 km', 'Berline', 'Amérique du Nord'),
                                                                                                                                                                                                                            (31, 16, 'B-Class 180', 'Essence', '2020', '4 cylindres', '1598 cm³', '136 ch', '200 Nm', '8.2 s', '210 km/h', '6.8 L/100 km', 'MPV', 'Europe'),
                                                                                                                                                                                                                            (32, 16, 'B-Class 220d', 'Diesel', '2021', '4 cylindres', '1991 cm³', '190 ch', '400 Nm', '7.5 s', '210 km/h', '5.7 L/100 km', 'MPV', 'Amérique du Nord'),
                                                                                                                                                                                                                            (33, 17, 'Grand Cherokee Laredo', 'Essence', '2020', 'V6', '3600 cm³', '290 ch', '348 Nm', '7.5 s', '220 km/h', '11.0 L/100 km', 'SUV', 'Europe'),
                                                                                                                                                                                                                            (34, 17, 'Grand Cherokee Overland', 'Essence', '2021', 'V8', '5700 cm³', '357 ch', '520 Nm', '6.0 s', '230 km/h', '13.0 L/100 km', 'SUV', 'Amérique du Nord'),
                                                                                                                                                                                                                            (35, 18, 'Q7 55 TFSI', 'Essence', '2020', 'V6', '2995 cm³', '335 ch', '500 Nm', '5.7 s', '250 km/h', '11.0 L/100 km', 'SUV', 'Europe'),
                                                                                                                                                                                                                            (36, 18, 'Q7 60 TDI', 'Diesel', '2021', 'V6', '2967 cm³', '340 ch', '600 Nm', '5.0 s', '240 km/h', '8.5 L/100 km', 'SUV', 'Asie'),
                                                                                                                                                                                                                            (37, 19, 'F-Pace 2.0', 'Essence', '2020', '4 cylindres turbo', '1997 cm³', '246 ch', '365 Nm', '6.0 s', '220 km/h', '9.5 L/100 km', 'SUV', 'Europe'),
                                                                                                                                                                                                                            (38, 19, 'F-Pace 3.0', 'Essence', '2021', 'V6', '2995 cm³', '395 ch', '550 Nm', '5.2 s', '250 km/h', '11.0 L/100 km', 'SUV', 'Amérique du Nord'),
                                                                                                                                                                                                                            (39, 20, 'NX 300h', 'Hybride', '2020', '4 cylindres + électrique', '2494 cm³', '194 ch', '280 Nm', '8.0 s', '200 km/h', '6.0 L/100 km', 'SUV', 'Europe'),
                                                                                                                                                                                                                            (40, 20, 'NX 350 F Sport', 'Essence', '2021', '4 cylindres turbo', '2359 cm³', '275 ch', '430 Nm', '6.2 s', '220 km/h', '8.5 L/100 km', 'SUV', 'Asie'),
                                                                                                                                                                                                                            (41, 21, 'Model S Long Range', 'Électrique', '2020', 'Électrique', '0 cm³', '670 ch', 'N/A', '3.7 s', '250 km/h', '18.0 L/100 km', 'Berline', 'Amérique du Nord'),
                                                                                                                                                                                                                            (42, 21, 'Model S Plaid', 'Électrique', '2021', 'Électrique', '0 cm³', '1020 ch', 'N/A', '2.1 s', '320 km/h', '20.0 L/100 km', 'Berline', 'Europe'),
                                                                                                                                                                                                                            (43, 22, 'E-Tron 50', 'Électrique', '2020', 'Électrique', '0 cm³', '230 ch', '540 Nm', '6.8 s', '200 km/h', '24.0 L/100 km', 'SUV', 'Europe'),
                                                                                                                                                                                                                            (44, 22, 'E-Tron 55', 'Électrique', '2021', 'Électrique', '0 cm³', '360 ch', '561 Nm', '5.7 s', '250 km/h', '22.0 L/100 km', 'SUV', 'Amérique du Nord'),
                                                                                                                                                                                                                            (45, 23, 'Q8 55 TFSI', 'Essence', '2020', 'V6', '2995 cm³', '335 ch', '500 Nm', '5.5 s', '250 km/h', '10.0 L/100 km', 'SUV', 'Europe'),
                                                                                                                                                                                                                            (46, 23, 'Q8 60 TDI', 'Diesel', '2021', 'V6', '2967 cm³', '340 ch', '600 Nm', '4.8 s', '240 km/h', '8.5 L/100 km', 'SUV', 'Asie'),
                                                                                                                                                                                                                            (47, 24, 'M3 Competition', 'Essence', '2020', '6 cylindres', '2993 cm³', '503 ch', '650 Nm', '4.1 s', '250 km/h', '10.0 L/100 km', 'Berline', 'Europe'),
                                                                                                                                                                                                                            (48, 24, 'M4 Competition', 'Essence', '2021', '6 cylindres', '2993 cm³', '503 ch', '650 Nm', '4.0 s', '250 km/h', '10.5 L/100 km', 'Coupé', 'Amérique du Nord'),
                                                                                                                                                                                                                            (49, 25, 'Panamera 4S', 'Essence', '2020', 'V6', '2894 cm³', '420 ch', '520 Nm', '4.0 s', '270 km/h', '11.0 L/100 km', 'Berline', 'Europe'),
                                                                                                                                                                                                                            (50, 25, 'Panamera GTS', 'Essence', '2021', 'V8', '3996 cm³', '453 ch', '620 Nm', '3.9 s', '280 km/h', '13.0 L/100 km', 'Berline', 'Amérique du Nord'),
                                                                                                                                                                                                                            (51, 26, '488 GTB', 'Essence', '2020', 'V8', '3902 cm³', '661 ch', '760 Nm', '3.0 s', '330 km/h', '14.0 L/100 km', 'Coupé', 'Europe'),
                                                                                                                                                                                                                            (52, 26, 'F8 Tributo', 'Essence', '2021', 'V8', '3902 cm³', '710 ch', '770 Nm', '2.9 s', '340 km/h', '15.0 L/100 km', 'Coupé', 'Amérique du Nord'),
                                                                                                                                                                                                                            (53, 27, 'LaFerrari FXX', 'Essence', '2020', 'V12 + hybride', '6262 cm³', '1036 ch', '900 Nm', '2.5 s', '355 km/h', '15.5 L/100 km', 'Coupé', 'Europe'),
                                                                                                                                                                                                                            (54, 27, 'LaFerrari XX', 'Essence', '2021', 'V12 + hybride', '6262 cm³', '950 ch', '900 Nm', '2.7 s', '350 km/h', '14.0 L/100 km', 'Coupé', 'Asie'),
                                                                                                                                                                                                                            (55, 28, 'Panamera Turbo S E-Hybrid', 'Hybride', '2020', 'V8 + électrique', '3996 cm³', '630 ch', '850 Nm', '3.2 s', '310 km/h', '15.0 L/100 km', 'Berline', 'Europe'),
                                                                                                                                                                                                                            (56, 28, 'Panamera Turbo SE-Hybrid', 'Hybride', '2021', 'V8 + électrique', '3996 cm³', '680 ch', '860 Nm', '3.0 s', '315 km/h', '16.0 L/100 km', 'Berline', 'Amérique du Nord'),
                                                                                                                                                                                                                            (57, 29, 'A8 L 60 TDI', 'Diesel', '2020', 'V6', '3130 cm³', '420 ch', '600 Nm', '5.0 s', '250 km/h', '9.0 L/100 km', 'Berline', 'Europe'),
                                                                                                                                                                                                                            (58, 29, 'A8 L 50 TDI', 'Diesel', '2021', 'V6', '2967 cm³', '335 ch', '500 Nm', '5.5 s', '240 km/h', '8.5 L/100 km', 'Berline', 'Amérique du Nord'),
                                                                                                                                                                                                                            (59, 30, 'B-Class 200', 'Essence', '2020', '4 cylindres', '1598 cm³', '163 ch', '250 Nm', '8.0 s', '220 km/h', '7.0 L/100 km', 'MPV', 'Europe'),
                                                                                                                                                                                                                            (60, 30, 'B-Class 250', 'Diesel', '2021', '4 cylindres', '1991 cm³', '224 ch', '400 Nm', '7.5 s', '210 km/h', '6.5 L/100 km', 'MPV', 'Amérique du Nord'),
                                                                                                                                                                                                                            (61, 31, 'Cherokee Latitude', 'Essence', '2020', 'V6', '3600 cm³', '290 ch', '348 Nm', '7.6 s', '220 km/h', '11.5 L/100 km', 'SUV', 'Europe'),
                                                                                                                                                                                                                            (62, 31, 'Cherokee Trailhawk', 'Essence', '2021', 'V6', '3600 cm³', '290 ch', '400 Nm', '7.2 s', '230 km/h', '12.0 L/100 km', 'SUV', 'Amérique du Nord'),
                                                                                                                                                                                                                            (63, 32, 'Q8 45 TDI', 'Diesel', '2020', 'V6', '2967 cm³', '340 ch', '600 Nm', '5.1 s', '240 km/h', '8.5 L/100 km', 'SUV', 'Europe'),
                                                                                                                                                                                                                            (64, 32, 'Q8 55 TDI', 'Diesel', '2021', 'V6', '2967 cm³', '340 ch', '600 Nm', '5.0 s', '250 km/h', '8.0 L/100 km', 'SUV', 'Amérique du Nord'),
                                                                                                                                                                                                                            (65, 33, 'F-Pace 2.0 R-Sport', 'Essence', '2020', '4 cylindres turbo', '1997 cm³', '250 ch', '365 Nm', '6.5 s', '230 km/h', '9.0 L/100 km', 'SUV', 'Europe'),
                                                                                                                                                                                                                            (66, 33, 'F-Pace 3.0 R-Sport', 'Essence', '2021', 'V6', '2995 cm³', '340 ch', '500 Nm', '5.5 s', '240 km/h', '11.0 L/100 km', 'SUV', 'Amérique du Nord'),
                                                                                                                                                                                                                            (67, 34, 'NX 300h F Sport', 'Hybride', '2020', '4 cylindres + électrique', '2494 cm³', '194 ch', '280 Nm', '8.0 s', '210 km/h', '6.2 L/100 km', 'SUV', 'Europe'),
                                                                                                                                                                                                                            (68, 34, 'NX 350 F Sport AWD', 'Essence', '2021', '4 cylindres turbo', '2359 cm³', '275 ch', '430 Nm', '6.3 s', '220 km/h', '8.0 L/100 km', 'SUV', 'Asie'),
                                                                                                                                                                                                                            (69, 35, 'Model X Long Range', 'Électrique', '2020', 'Électrique', '0 cm³', '670 ch', 'N/A', '4.4 s', '250 km/h', '18.0 L/100 km', 'SUV', 'Amérique du Nord'),
                                                                                                                                                                                                                            (70, 35, 'Model X Plaid', 'Électrique', '2021', 'Électrique', '0 cm³', '1020 ch', 'N/A', '2.6 s', '320 km/h', '20.0 L/100 km', 'SUV', 'Europe'),
                                                                                                                                                                                                                            (71, 36, 'Model 3 Standard Plus', 'Électrique', '2020', 'Électrique', '0 cm³', '283 ch', 'N/A', '5.3 s', '225 km/h', '16.0 L/100 km', 'Berline', 'Amérique du Nord'),
                                                                                                                                                                                                                            (72, 36, 'Model 3 Performance', 'Électrique', '2021', 'Électrique', '0 cm³', '450 ch', 'N/A', '3.2 s', '250 km/h', '18.0 L/100 km', 'Berline', 'Europe');


ALTER TABLE fiche_type AUTO_INCREMENT = 1;
-- Association entre les fiches et les types de véhicules
INSERT INTO `fiche_type` (`ID`, `ID_FICHE`, `ID_TYPE`) VALUES
                                                           (1, 1, 1), -- Civic LX : Berline
                                                           (2, 1, 6), -- Civic LX : Crossover
                                                           (3, 2, 1), -- Civic EX : Berline
                                                           (4, 2, 6), -- Civic EX : Crossover
                                                           (5, 3, 10), -- Mustang GT : Supercar
                                                           (6, 3, 11), -- Mustang GT : Tout-terrain
                                                           (7, 4, 10), -- Mustang EcoBoost : Supercar
                                                           (8, 4, 11), -- Mustang EcoBoost : Tout-terrain
                                                           (9, 5, 1), -- 3 Series 320i : Berline
                                                           (10, 5, 6), -- 3 Series 320i : Crossover
                                                           (11, 6, 1), -- 3 Series 330i : Berline
                                                           (12, 6, 6), -- 3 Series 330i : Crossover
                                                           (13, 7, 5), -- F-150 XLT : Camion
                                                           (14, 7, 11), -- F-150 XLT : Tout-terrain
                                                           (15, 8, 5), -- F-150 Lariat : Camion
                                                           (16, 8, 11), -- F-150 Lariat : Tout-terrain
                                                           (17, 9, 3), -- Civic Type R : Coupé
                                                           (18, 9, 6), -- Civic Type R : Crossover
                                                           (19, 10, 3), -- Civic Si : Coupé
                                                           (20, 10, 6), -- Civic Si : Crossover
                                                           (21, 11, 6), -- X5 xDrive40i : Crossover
                                                           (22, 11, 11), -- X5 xDrive40i : Tout-terrain
                                                           (23, 12, 6), -- X5 xDrive50i : Crossover
                                                           (24, 12, 11), -- X5 xDrive50i : Tout-terrain
                                                           (25, 13, 6), -- Macan S : Crossover
                                                           (26, 13, 11), -- Macan S : Tout-terrain
                                                           (27, 14, 6), -- Macan Turbo : Crossover
                                                           (28, 14, 11), -- Macan Turbo : Tout-terrain
                                                           (29, 15, 1), -- A8 50 TDI : Berline
                                                           (30, 15, 12), -- A8 50 TDI : Limousine
                                                           (31, 16, 1), -- A8 55 TFSI : Berline
                                                           (32, 16, 12); -- A8 55 TFSI : Limousine



