-- Insertion des données dans la table `annee_tranche`

INSERT INTO `annee_tranche` (`NOM_ANNEE_TRANCHE`) VALUES
                                                      ('1900-1910'),
                                                      ('1911-1920'),
                                                      ('1921-1930'),
                                                      ('1931-1940'),
                                                      ('1941-1950'),
                                                      ('1951-1960'),
                                                      ('1961-1970'),
                                                      ('1971-1980'),
                                                      ('1981-1990'),
                                                      ('1991-2000'),
                                                      ('2001-2010'),
                                                      ('2011-2020'),
                                                      ('2021-2030');

-- Insertion des années dans la table `annee`

INSERT INTO `annee` (`NOM_ANNEE`, `ID_DECENNIE`) VALUES
-- Tranche 1900-1910
('1900', 1),
('1901', 1),
('1902', 1),
('1903', 1),
('1904', 1),
('1905', 1),
('1906', 1),
('1907', 1),
('1908', 1),
('1909', 1),
('1910', 1),
-- Tranche 1911-1920
('1911', 2),
('1912', 2),
('1913', 2),
('1914', 2),
('1915', 2),
('1916', 2),
('1917', 2),
('1918', 2),
('1919', 2),
('1920', 2),
-- Tranche 1921-1930
('1921', 3),
('1922', 3),
('1923', 3),
('1924', 3),
('1925', 3),
('1926', 3),
('1927', 3),
('1928', 3),
('1929', 3),
('1930', 3),
-- Tranche 1931-1940
('1931', 4),
('1932', 4),
('1933', 4),
('1934', 4),
('1935', 4),
('1936', 4),
('1937', 4),
('1938', 4),
('1939', 4),
('1940', 4),
-- Tranche 1941-1950
('1941', 5),
('1942', 5),
('1943', 5),
('1944', 5),
('1945', 5),
('1946', 5),
('1947', 5),
('1948', 5),
('1949', 5),
('1950', 5),
-- Tranche 1951-1960
('1951', 6),
('1952', 6),
('1953', 6),
('1954', 6),
('1955', 6),
('1956', 6),
('1957', 6),
('1958', 6),
('1959', 6),
('1960', 6),
-- Tranche 1961-1970
('1961', 7),
('1962', 7),
('1963', 7),
('1964', 7),
('1965', 7),
('1966', 7),
('1967', 7),
('1968', 7),
('1969', 7),
('1970', 7),
-- Tranche 1971-1980
('1971', 8),
('1972', 8),
('1973', 8),
('1974', 8),
('1975', 8),
('1976', 8),
('1977', 8),
('1978', 8),
('1979', 8),
('1980', 8),
-- Tranche 1981-1990
('1981', 9),
('1982', 9),
('1983', 9),
('1984', 9),
('1985', 9),
('1986', 9),
('1987', 9),
('1988', 9),
('1989', 9),
('1990', 9),
-- Tranche 1991-2000
('1991', 10),
('1992', 10),
('1993', 10),
('1994', 10),
('1995', 10),
('1996', 10),
('1997', 10),
('1998', 10),
('1999', 10),
('2000', 10),
-- Tranche 2001-2010
('2001', 11),
('2002', 11),
('2003', 11),
('2004', 11),
('2005', 11),
('2006', 11),
('2007', 11),
('2008', 11),
('2009', 11),
('2010', 11),
-- Tranche 2011-2020
('2011', 12),
('2012', 12),
('2013', 12),
('2014', 12),
('2015', 12),
('2016', 12),
('2017', 12),
('2018', 12),
('2019', 12),
('2020', 12),
-- Tranche 2021-2030
('2021', 13),
('2022', 13),
('2023', 13),
('2024', 13),
('2025', 13),
('2026', 13),
('2027', 13),
('2028', 13),
('2029', 13),
('2030', 13);


-- Insertion des pays dans la table `pays`

INSERT INTO `pays` (`NOM_PAYS`) VALUES
                                    ('Afghanistan'),
                                    ('Albanie'),
                                    ('Algérie'),
                                    ('Andorre'),
                                    ('Angola'),
                                    ('Antigua-et-Barbuda'),
                                    ('Argentine'),
                                    ('Arménie'),
                                    ('Australie'),
                                    ('Autriche'),
                                    ('Azerbaïdjan'),
                                    ('Bahamas'),
                                    ('Bahreïn'),
                                    ('Bangladesh'),
                                    ('Barbade'),
                                    ('Bélarus'),
                                    ('Belgique'),
                                    ('Belize'),
                                    ('Bénin'),
                                    ('Bhoutan'),
                                    ('Bolivie'),
                                    ('Bosnie-Herzégovine'),
                                    ('Botswana'),
                                    ('Brésil'),
                                    ('Brunei'),
                                    ('Bulgarie'),
                                    ('Burkina Faso'),
                                    ('Burundi'),
                                    ('Cabo Verde'),
                                    ('Cambodge'),
                                    ('Cameroun'),
                                    ('Canada'),
                                    ('Centrafrique'),
                                    ('Chili'),
                                    ('Chine'),
                                    ('Colombie'),
                                    ('Comores'),
                                    ('Congo'),
                                    ('Congo (RDC)'),
                                    ('Costa Rica'),
                                    ('Croatie'),
                                    ('Cuba'),
                                    ('Chypre'),
                                    ('République tchèque'),
                                    ('Danemark'),
                                    ('Djibouti'),
                                    ('Dominique'),
                                    ('Égypte'),
                                    ('Équateur'),
                                    ('Érythrée'),
                                    ('Espagne'),
                                    ('Estonie'),
                                    ('Eswatini'),
                                    ('États-Unis'),
                                    ('Éthiopie'),
                                    ('Fidji'),
                                    ('Finlande'),
                                    ('France'),
                                    ('Gabon'),
                                    ('Gambie'),
                                    ('Géorgie'),
                                    ('Ghana'),
                                    ('Grèce'),
                                    ('Grenade'),
                                    ('Guatemala'),
                                    ('Guinée'),
                                    ('Guinée-Bissau'),
                                    ('Guyane'),
                                    ('Haïti'),
                                    ('Honduras'),
                                    ('Hongrie'),
                                    ('Iles Cook'),
                                    ('Iles Marshall'),
                                    ('Inde'),
                                    ('Indonésie'),
                                    ('Iran'),
                                    ('Irak'),
                                    ('Irlande'),
                                    ('Islande'),
                                    ('Israël'),
                                    ('Italie'),
                                    ('Jamaïque'),
                                    ('Japon'),
                                    ('Jordanie'),
                                    ('Kazakhstan'),
                                    ('Kenya'),
                                    ('Kirghizistan'),
                                    ('Kiribati'),
                                    ('Koweït'),
                                    ('Laos'),
                                    ('Latvia'),
                                    ('Liban'),
                                    ('Liberia'),
                                    ('Libye'),
                                    ('Liechtenstein'),
                                    ('Lituanie'),
                                    ('Luxembourg'),
                                    ('Madagascar'),
                                    ('Malaisie'),
                                    ('Malawi'),
                                    ('Maldives'),
                                    ('Mali'),
                                    ('Malte'),
                                    ('Maroc'),
                                    ('Maurice'),
                                    ('Mauritanie'),
                                    ('Mexique'),
                                    ('Micronésie'),
                                    ('Moldavie'),
                                    ('Monaco'),
                                    ('Mongolie'),
                                    ('Monténégro'),
                                    ('Maroc'),
                                    ('Mozambique'),
                                    ('Myanmar'),
                                    ('Namibie'),
                                    ('Nauru'),
                                    ('Népal'),
                                    ('Niger'),
                                    ('Nigéria'),
                                    ('Norvège'),
                                    ('Nouvelle-Zélande'),
                                    ('Oman'),
                                    ('Ouganda'),
                                    ('Ouzbékistan'),
                                    ('Pakistan'),
                                    ('Palaos'),
                                    ('Panama'),
                                    ('Papouasie-Nouvelle-Guinée'),
                                    ('Paraguay'),
                                    ('Pays-Bas'),
                                    ('Pérou'),
                                    ('Philippines'),
                                    ('Pologne'),
                                    ('Portugal'),
                                    ('Qatar'),
                                    ('Roumanie'),
                                    ('Royaume-Uni'),
                                    ('Rwanda'),
                                    ('Saint-Kitts-et-Nevis'),
                                    ('Saint-Lucie'),
                                    ('Saint-Vincent-et-les-Grenadines'),
                                    ('Salvador'),
                                    ('Samoa'),
                                    ('San Marin'),
                                    ('Sao Tomé-et-Principe'),
                                    ('Arabie Saoudite'),
                                    ('Sénégal'),
                                    ('Serbie'),
                                    ('Seychelles'),
                                    ('Sierra Leone'),
                                    ('Singapour'),
                                    ('Slovaquie'),
                                    ('Slovénie'),
                                    ('Somalie'),
                                    ('Soudan'),
                                    ('Soudan du Sud'),
                                    ('Sri Lanka'),
                                    ('Suède'),
                                    ('Suisse'),
                                    ('Syrie'),
                                    ('Tadjikistan'),
                                    ('Tanzanie'),
                                    ('Thailande'),
                                    ('Timor-Leste'),
                                    ('Togo'),
                                    ('Trinité-et-Tobago'),
                                    ('Tunisie'),
                                    ('Turkménistan'),
                                    ('Turquie'),
                                    ('Tuvalu'),
                                    ('Ukraine'),
                                    ('Uruguay'),
                                    ('Vanuatu'),
                                    ('Vatican'),
                                    ('Venezuela'),
                                    ('Vietnam'),
                                    ('Yémen'),
                                    ('Zambie'),
                                    ('Zimbabwe');

-- Insertion des groupes automobiles dans la table `groupe`

INSERT INTO `groupe` (`NOM_GROUPE`) VALUES
                                        ('Volkswagen Group'),
                                        ('Toyota Motor Corporation'),
                                        ('General Motors'),
                                        ('Ford Motor Company'),
                                        ('Honda Motor Co.'),
                                        ('BMW Group'),
                                        ('Daimler AG'),
                                        ('Nissan Motor Corporation'),
                                        ('Hyundai Motor Group'),
                                        ('Fiat Chrysler Automobiles'),
                                        ('Renault-Nissan-Mitsubishi Alliance'),
                                        ('Subaru Corporation'),
                                        ('Mazda Motor Corporation'),
                                        ('Tesla, Inc.'),
                                        ('Jaguar Land Rover'),
                                        ('SAIC Motor Corporation'),
                                        ('Geely Automobile'),
                                        ('Changan Automobile'),
                                        ('Great Wall Motors'),
                                        ('BYD Auto'),
                                        ('Porsche AG'),
                                        ('Audi AG'),
                                        ('Lexus'),
                                        ('Infiniti'),
                                        ('Cadillac'),
                                        ('Buick'),
                                        ('GMC'),
                                        ('Chrysler'),
                                        ('Dodge'),
                                        ('Ram'),
                                        ('Aston Martin'),
                                        ('Ferrari'),
                                        ('Lamborghini'),
                                        ('McLaren'),
                                        ('Pagani'),
                                        ('Koenigsegg'),
                                        ('Lotus Cars'),
                                        ('Peugeot'),
                                        ('Citroën'),
                                        ('DS Automobiles'),
                                        ('Alfa Romeo'),
                                        ('Lancia'),
                                        ('Opel'),
                                        ('Vauxhall'),
                                        ('Skoda'),
                                        ('Seat'),
                                        ('Iveco'),
                                        ('MAN Truck & Bus'),
                                        ('Scania AB'),
                                        ('Hino Motors'),
                                        ('Isuzu Motors'),
                                        ('Fuso'),
                                        ('Freightliner'),
                                        ('Kenworth'),
                                        ('Peterbilt'),
                                        ('Mack Trucks'),
                                        ('Navistar International'),
                                        ('Autocar'),
                                        ('Western Star Trucks'),
                                        ('Blue Bird Corporation'),
                                        ('Thomas Built Buses'),
                                        ('IC Bus'),
                                        ('Groupe PSA'),
                                        ('Groupe Renault'),
                                        ('Mitsubishi Motors'),
                                        ('Tata Motors'),
                                        ('Mahindra & Mahindra'),
                                        ('Maruti Suzuki'),
                                        ('Suzuki Motor Corporation'),
                                        ('Hummer'),
                                        ('Wuling Motors'),
                                        ('Daimler Truck'),
                                        ('NIO Inc.'),
                                        ('XPeng Motors'),
                                        ('Rivian Automotive'),
                                        ('Lucid Motors'),
                                        ('Polestar'),
                                        ('Bollinger Motors'),
                                        ('Fisker Inc.'),
                                        ('Faraday Future'),
                                        ('Lucid Motors'),
                                        ('Aiways'),
                                        ('Rimac Automobili'),
                                        ('Silk EV'),
                                        ('Vanda Electrics'),
                                        ('Atieva'),
                                        ('Envision AESC'),
                                        ('Karma Automotive'),
                                        ('Arrival'),
                                        ('Proterra'),
                                        ('Electra Meccanica'),
                                        ('Arcimoto'),
                                        ('Canoo'),
                                        ('Lordstown Motors'),
                                        ('SAYCAR'),
                                        ('Solo Motors'),
                                        ('Eli Electric Vehicles'),
                                        ('The Rayton-Fissore'),
                                        ('Pal-V'),
                                        ('Terrafugia'),
                                        ('Urban Aeronautics'),
                                        ('Joby Aviation'),
                                        ('Vertical Aerospace'),
                                        ('Lilium'),
                                        ('EHang'),
                                        ('Aurora Flight Sciences'),
                                        ('Wingcopter'),
                                        ('Zipline'),
                                        ('Matternet'),
                                        ('Dronamics'),
                                        ('Elroy Air');

-- Insertion des constructeurs dans la table `constructeur`

INSERT INTO `constructeur` (`NOM_CONSTRUCTEUR`, `ID_PAYS`, `ID_GROUPE`) VALUES
                                                                            ('Volkswagen', 35, 1),
                                                                            ('Toyota', 9, 2),
                                                                            ('General Motors', 54, 3),
                                                                            ('Ford', 54, 4),
                                                                            ('Honda', 9, 5),
                                                                            ('BMW', 10, 6),
                                                                            ('Daimler', 10, 7),
                                                                            ('Nissan', 9, 8),
                                                                            ('Hyundai', 9, 9),
                                                                            ('Fiat', 10, 10),
                                                                            ('Renault', 51, 11),
                                                                            ('Subaru', 9, 12),
                                                                            ('Mazda', 9, 13),
                                                                            ('Tesla', 54, 14),
                                                                            ('Jaguar', 138, 15),
                                                                            ('SAIC Motor', 35, 16),
                                                                            ('Geely', 35, 17),
                                                                            ('Changan', 35, 18),
                                                                            ('Great Wall Motors', 35, 19),
                                                                            ('BYD', 35, 20),
                                                                            ('Porsche', 10, 21),
                                                                            ('Audi', 10, 22),
                                                                            ('Lexus', 9, 23),
                                                                            ('Infiniti', 9, 24),
                                                                            ('Cadillac', 54, 25),
                                                                            ('Buick', 54, 26),
                                                                            ('GMC', 54, 27),
                                                                            ('Chrysler', 54, 28),
                                                                            ('Dodge', 54, 29),
                                                                            ('Ram', 54, 30),
                                                                            ('Aston Martin', 138, 31),
                                                                            ('Ferrari', 10, 32),
                                                                            ('Lamborghini', 10, 33),
                                                                            ('McLaren', 138, 34),
                                                                            ('Pagani', 10, 35),
                                                                            ('Koenigsegg', 179, 36),
                                                                            ('Lotus', 138, 37),
                                                                            ('Peugeot', 51, 38),
                                                                            ('Citroën', 51, 39),
                                                                            ('DS Automobiles', 51, 40),
                                                                            ('Alfa Romeo', 10, 41),
                                                                            ('Lancia', 10, 42),
                                                                            ('Opel', 51, 43),
                                                                            ('Vauxhall', 51, 44),
                                                                            ('Skoda', 35, 45),
                                                                            ('Seat', 35, 46),
                                                                            ('Iveco', 10, 47),
                                                                            ('MAN', 10, 48),
                                                                            ('Scania', 10, 49),
                                                                            ('Hino', 9, 50),
                                                                            ('Isuzu', 9, 51),
                                                                            ('Fuso', 9, 52),
                                                                            ('Freightliner', 54, 53),
                                                                            ('Kenworth', 54, 54),
                                                                            ('Peterbilt', 54, 55),
                                                                            ('Mack', 54, 56),
                                                                            ('Navistar', 54, 57),
                                                                            ('Autocar', 54, 58),
                                                                            ('Western Star', 54, 59),
                                                                            ('Blue Bird', 54, 60),
                                                                            ('Thomas Built Buses', 54, 61),
                                                                            ('IC Bus', 54, 62),
                                                                            ('Groupe PSA', 51, 63),
                                                                            ('Groupe Renault', 51, 64),
                                                                            ('Mitsubishi', 9, 65),
                                                                            ('Tata Motors', 149, 66),
                                                                            ('Mahindra', 149, 67),
                                                                            ('Maruti Suzuki', 9, 68),
                                                                            ('Suzuki', 9, 69),
                                                                            ('Hummer', 54, 70),
                                                                            ('Wuling', 35, 71),
                                                                            ('Daimler Truck', 10, 72),
                                                                            ('NIO', 35, 73),
                                                                            ('XPeng', 35, 74),
                                                                            ('Rivian', 54, 75),
                                                                            ('Lucid Motors', 54, 76),
                                                                            ('Polestar', 10, 77),
                                                                            ('Bollinger Motors', 54, 78),
                                                                            ('Fisker', 54, 79),
                                                                            ('Faraday Future', 54, 80),
                                                                            ('Aiways', 35, 82),
                                                                            ('Rimac Automobili', 179, 83),
                                                                            ('Silk EV', 35, 84),
                                                                            ('Vanda Electrics', 35, 85),
                                                                            ('Atieva', 54, 86),
                                                                            ('Envision AESC', 35, 87),
                                                                            ('Karma Automotive', 54, 88),
                                                                            ('Arrival', 54, 89),
                                                                            ('Proterra', 54, 90),
                                                                            ('Electra Meccanica', 54, 91),
                                                                            ('Arcimoto', 54, 92),
                                                                            ('Canoo', 54, 93),
                                                                            ('Lordstown Motors', 54, 94),
                                                                            ('SAYCAR', 54, 95),
                                                                            ('Solo Motors', 54, 96),
                                                                            ('Eli Electric Vehicles', 54, 97),
                                                                            ('The Rayton-Fissore', 54, 98),
                                                                            ('Pal-V', 54, 99),
                                                                            ('Terrafugia', 54, 100),
                                                                            ('Urban Aeronautics', 54, 101),
                                                                            ('Joby Aviation', 54, 102),
                                                                            ('Vertical Aerospace', 54, 103),
                                                                            ('Lilium', 54, 104),
                                                                            ('EHang', 54, 105),
                                                                            ('Aurora Flight Sciences', 54, 106),
                                                                            ('Wingcopter', 54, 107),
                                                                            ('Zipline', 54, 108),
                                                                            ('Matternet', 54, 109),
                                                                            ('Dronamics', 54, 110),
                                                                            ('Elroy Air', 54, 111);

-- Insertion des données dans la table `segment`

INSERT INTO `segment` (`NOM_SEGMENT`) VALUES
                                          ('A - Mini'),
                                          ('B - Sous-compacte'),
                                          ('C - Compacte'),
                                          ('D - Intermédiaire'),
                                          ('E - Grosse voiture'),
                                          ('F - Luxe'),
                                          ('G - Fourgonnette'),
                                          ('H - Course');


-- Insertion des données dans la table `type`

INSERT INTO `type` (`NOM_TYPE`) VALUES
                                    ('Berline'),
                                    ('Break'),
                                    ('Coupé'),
                                    ('Cabriolet'),
                                    ('Camion'),
                                    ('Crossover'),
                                    ('Fourgon'),
                                    ('Prototype'),
                                    ('Roadster'),
                                    ('Supercar'),
                                    ('Tout-terrain'),
                                    ('Limousine');
